# Generated by Django 5.2.1 on 2025-06-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectapp', '0002_tshirt'),
    ]

    operations = [
        migrations.AddField(
            model_name='tshirt',
            name='price',
            field=models.DecimalField(decimal_places=2, default=299.0, max_digits=6),
        ),
    ]
