# Generated by Django 5.2.1 on 2025-07-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectapp', '0003_tshirt_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tshirt',
            name='design_image',
            field=models.ImageField(blank=True, null=True, upload_to='tshirt_designs/'),
        ),
    ]
