# Generated by Django 5.2.1 on 2025-07-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectapp', '0004_alter_tshirt_design_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tshirt',
            name='color',
            field=models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('black', 'Black'), ('white', 'White'), ('green', 'Green')], max_length=10),
        ),
    ]
