# Generated by Django 5.2.1 on 2025-07-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectapp', '0005_alter_tshirt_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tshirt',
            name='color',
            field=models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('black', 'Black'), ('white', 'White'), ('green', 'Green')], default='red', max_length=10),
        ),
        migrations.AlterField(
            model_name='tshirt',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], default='M', max_length=2),
        ),
    ]
