# Generated by Django 5.2.1 on 2025-07-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectapp', '0006_alter_tshirt_color_alter_tshirt_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tshirt',
            name='color',
            field=models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('black', 'Black'), ('white', 'White'), ('green', 'Green')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tshirt',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=2),
        ),
    ]
