# Generated by Django 5.2.4 on 2025-07-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectapp', '0007_alter_tshirt_color_alter_tshirt_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaunchNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
